#include "B_Vektor.h"
#include "Constants.h"
#include <future>

std::vector<long double> B_Vektor::vektor(std::vector<wire_part>* parts_pointer, long double x, long double y, long double z)
{
	std::vector<long double> gesamt = { 0,0,0 };


	for (const wire_part& part : *parts_pointer) { //for every wirepart generated
		std::vector<long double> diff = { //vector wirepart -> position of field
			(x - part.x) ,
			(y - part.y) ,
			(z - part.z) ,
		};
		long double r = sqrt(pow(diff[0], 2) + pow(diff[1], 2) + pow(diff[2], 2)); //value of vector wirepart -> position of field
		std::vector<long double> kreuzvektor = {
			(part.wirepart_y * diff[2] - part.wirepart_z * diff[1]) * (4 * PI) / pow(r, 3) , //x
			(part.wirepart_z * diff[0] - part.wirepart_x * diff[2]) * (4 * PI) / pow(r, 3) , //y
			(part.wirepart_x * diff[1] - part.wirepart_y * diff[0]) * (4 * PI) / pow(r, 3) , //z
		};
		gesamt[0] += kreuzvektor[0]; gesamt[1] += kreuzvektor[1]; gesamt[2] += kreuzvektor[2]; //adds magentic field generated by current 
																							   //wirepart to total
	}
	return gesamt;
}